// Generated by scripts/sync-tool-schemas.mjs; edit the backend canonical source.
/** Canonical configuration envelope; copied to the MCP package by sync-tool-schemas. */
export const toolFieldSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['name', 'type', 'label', 'required'],
  properties: {
    name: { type: 'string', pattern: '^[a-zA-Z][a-zA-Z0-9_-]*$' },
    type: { type: 'string', enum: ['string', 'number', 'boolean', 'date', 'enum'] },
    label: { type: 'string', minLength: 1 },
    required: { type: 'boolean' },
    description: { type: 'string' },
    enumValues: { type: 'array', minItems: 1, uniqueItems: true, items: { type: 'string' } },
    validation: {
      type: 'object',
      additionalProperties: false,
      properties: {
        min: { type: 'number' },
        max: { type: 'number' },
        pattern: { type: 'string', format: 'regex' },
        maxLength: { type: 'integer', minimum: 0 }
      }
    }
  },
  allOf: [{ if: { properties: { type: { const: 'enum' } } }, then: { required: ['enumValues'] } }]
}

export const toolConfigSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    baseTool: { type: 'string', pattern: '^[a-zA-Z][a-zA-Z0-9_-]*$' },
    connector: { type: 'string', minLength: 1 },
    params: { type: 'object', additionalProperties: true },
    fields: { type: 'array', items: toolFieldSchema },
    instruction: { type: 'string' }
  }
}

/** Known authoring fields; extension fields remain supported by the agent API. */
export const partialAgentConfigSchema = {
  type: 'object',
  additionalProperties: true,
  properties: {
    name: { type: 'string' },
    identity: {
      type: 'object',
      properties: {
        tone: { type: 'string' },
        language: { type: 'string' },
        objective: { type: 'string' },
        customInstructions: { type: 'string' }
      }
    },
    enabledTools: { type: 'array', uniqueItems: true, items: { type: 'string' } },
    toolConfigs: { type: 'object', additionalProperties: toolConfigSchema },
    stages: {
      type: 'array',
      items: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { type: 'string', minLength: 1 },
          name: { type: 'string' },
          instruction: { type: 'string' },
          type: { type: 'string', enum: ['start', 'action', 'router', 'end'] },
          tools: { type: 'array', items: { type: 'string' } }
        }
      }
    },
    channels: { type: 'array', items: { type: 'string' } }
  }
}
